// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.contentunderstanding.implementation.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The CopyRequest model.
 */
@Fluent
public final class CopyRequest implements JsonSerializable<CopyRequest> {
    /*
     * Azure resource ID of the source analyzer location. Defaults to the current resource.
     */
    @Generated
    private String sourceAzureResourceId;

    /*
     * Azure region of the source analyzer location. Defaults to current region.
     */
    @Generated
    private String sourceRegion;

    /*
     * Source analyzer ID.
     */
    @Generated
    private final String sourceAnalyzerId;

    /**
     * Creates an instance of CopyRequest class.
     * 
     * @param sourceAnalyzerId the sourceAnalyzerId value to set.
     */
    @Generated
    public CopyRequest(String sourceAnalyzerId) {
        this.sourceAnalyzerId = sourceAnalyzerId;
    }

    /**
     * Get the sourceAzureResourceId property: Azure resource ID of the source analyzer location. Defaults to the
     * current resource.
     * 
     * @return the sourceAzureResourceId value.
     */
    @Generated
    public String getSourceAzureResourceId() {
        return this.sourceAzureResourceId;
    }

    /**
     * Set the sourceAzureResourceId property: Azure resource ID of the source analyzer location. Defaults to the
     * current resource.
     * 
     * @param sourceAzureResourceId the sourceAzureResourceId value to set.
     * @return the CopyRequest object itself.
     */
    @Generated
    public CopyRequest setSourceAzureResourceId(String sourceAzureResourceId) {
        this.sourceAzureResourceId = sourceAzureResourceId;
        return this;
    }

    /**
     * Get the sourceRegion property: Azure region of the source analyzer location. Defaults to current region.
     * 
     * @return the sourceRegion value.
     */
    @Generated
    public String getSourceRegion() {
        return this.sourceRegion;
    }

    /**
     * Set the sourceRegion property: Azure region of the source analyzer location. Defaults to current region.
     * 
     * @param sourceRegion the sourceRegion value to set.
     * @return the CopyRequest object itself.
     */
    @Generated
    public CopyRequest setSourceRegion(String sourceRegion) {
        this.sourceRegion = sourceRegion;
        return this;
    }

    /**
     * Get the sourceAnalyzerId property: Source analyzer ID.
     * 
     * @return the sourceAnalyzerId value.
     */
    @Generated
    public String getSourceAnalyzerId() {
        return this.sourceAnalyzerId;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("sourceAnalyzerId", this.sourceAnalyzerId);
        jsonWriter.writeStringField("sourceAzureResourceId", this.sourceAzureResourceId);
        jsonWriter.writeStringField("sourceRegion", this.sourceRegion);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of CopyRequest from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of CopyRequest if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the CopyRequest.
     */
    @Generated
    public static CopyRequest fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String sourceAnalyzerId = null;
            String sourceAzureResourceId = null;
            String sourceRegion = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("sourceAnalyzerId".equals(fieldName)) {
                    sourceAnalyzerId = reader.getString();
                } else if ("sourceAzureResourceId".equals(fieldName)) {
                    sourceAzureResourceId = reader.getString();
                } else if ("sourceRegion".equals(fieldName)) {
                    sourceRegion = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            CopyRequest deserializedCopyRequest = new CopyRequest(sourceAnalyzerId);
            deserializedCopyRequest.sourceAzureResourceId = sourceAzureResourceId;
            deserializedCopyRequest.sourceRegion = sourceRegion;

            return deserializedCopyRequest;
        });
    }
}
