// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.contentunderstanding.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * Detected person.
 */
@Immutable
public final class DetectedPerson implements JsonSerializable<DetectedPerson> {
    /*
     * Person identifier in the optional person directory if found. Otherwise, each unknown person is assigned a unique
     * `Person-{Number}`.
     */
    @Generated
    private String personId;

    /*
     * Confidence of the person identification, if a person directory is provided.
     */
    @Generated
    private Double confidence;

    /*
     * Encoded source that identifies the position of the person in the input content.
     */
    @Generated
    private String source;

    /**
     * Creates an instance of DetectedPerson class.
     */
    @Generated
    private DetectedPerson() {
    }

    /**
     * Get the personId property: Person identifier in the optional person directory if found. Otherwise, each unknown
     * person is assigned a unique `Person-{Number}`.
     * 
     * @return the personId value.
     */
    @Generated
    public String getPersonId() {
        return this.personId;
    }

    /**
     * Get the confidence property: Confidence of the person identification, if a person directory is provided.
     * 
     * @return the confidence value.
     */
    @Generated
    public Double getConfidence() {
        return this.confidence;
    }

    /**
     * Get the source property: Encoded source that identifies the position of the person in the input content.
     * 
     * @return the source value.
     */
    @Generated
    public String getSource() {
        return this.source;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("personId", this.personId);
        jsonWriter.writeNumberField("confidence", this.confidence);
        jsonWriter.writeStringField("source", this.source);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of DetectedPerson from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of DetectedPerson if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IOException If an error occurs while reading the DetectedPerson.
     */
    @Generated
    public static DetectedPerson fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            DetectedPerson deserializedDetectedPerson = new DetectedPerson();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("personId".equals(fieldName)) {
                    deserializedDetectedPerson.personId = reader.getString();
                } else if ("confidence".equals(fieldName)) {
                    deserializedDetectedPerson.confidence = reader.getNullable(JsonReader::getDouble);
                } else if ("source".equals(fieldName)) {
                    deserializedDetectedPerson.source = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedDetectedPerson;
        });
    }
}
