// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.contentunderstanding.models;

import com.azure.core.annotation.Generated;
import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Status of a resource.
 */
public final class ResourceStatus extends ExpandableStringEnum<ResourceStatus> {
    /**
     * The resource is being created.
     */
    @Generated
    public static final ResourceStatus CREATING = fromString("creating");

    /**
     * The resource is ready.
     */
    @Generated
    public static final ResourceStatus READY = fromString("ready");

    /**
     * The resource is being deleted.
     */
    @Generated
    public static final ResourceStatus DELETING = fromString("deleting");

    /**
     * The resource failed during creation.
     */
    @Generated
    public static final ResourceStatus FAILED = fromString("failed");

    /**
     * Creates a new instance of ResourceStatus value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Generated
    @Deprecated
    public ResourceStatus() {
    }

    /**
     * Creates or finds a ResourceStatus from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding ResourceStatus.
     */
    @Generated
    public static ResourceStatus fromString(String name) {
        return fromString(name, ResourceStatus.class);
    }

    /**
     * Gets known ResourceStatus values.
     * 
     * @return known ResourceStatus values.
     */
    @Generated
    public static Collection<ResourceStatus> values() {
        return values(ResourceStatus.class);
    }
}
