// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.contentunderstanding.models;

import com.azure.core.annotation.Generated;
import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * String encoding format.
 */
public final class StringEncoding extends ExpandableStringEnum<StringEncoding> {
    /**
     * Unicode code point (UTF-32) encoding, used by languages such as Python, etc.
     */
    @Generated
    public static final StringEncoding CODE_POINT = fromString("codePoint");

    /**
     * UTF-16 encoding, used by languages such as C#, JavaScript, Java, etc.
     */
    @Generated
    public static final StringEncoding UTF16 = fromString("utf16");

    /**
     * UTF-8 encoding, used by languages such as Go, Rust, Ruby, PHP, etc.
     */
    @Generated
    public static final StringEncoding UTF8 = fromString("utf8");

    /**
     * Creates a new instance of StringEncoding value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Generated
    @Deprecated
    public StringEncoding() {
    }

    /**
     * Creates or finds a StringEncoding from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding StringEncoding.
     */
    @Generated
    public static StringEncoding fromString(String name) {
        return fromString(name, StringEncoding.class);
    }

    /**
     * Gets known StringEncoding values.
     * 
     * @return known StringEncoding values.
     */
    @Generated
    public static Collection<StringEncoding> values() {
        return values(StringEncoding.class);
    }
}
